"experiments":
  "0":
    prompt_init: "a professional imaging of a modern style black house with blue windows and small garden"
    prompt_new: [
        "a professional imaging of a modern style black house with green windows and small garden",
    ]
    img_path: ""
    steps: 50
    scale: 7.5
    self_replace_steps: 0.4
    cross_replace_steps: 0.8

    # modes
    localize:
      apply: True
      words: ["windows", "windows"]
    reweight:
      apply: True
      text: ["green"]
      weights: [-1, 1, 2, 4, 8]
    refine:
      apply: True
    replace:
      apply: False
  "1":
    prompt_init: "a professional imaging of a house with a small garden"
    prompt_new: [
        "a professional imaging of a house with a small garden",
    ]
    img_path: ""
    steps: 50
    scale: 7.5
    self_replace_steps: 0.4
    cross_replace_steps: 0.8

    # modes
    localize:
      apply: True
      words: ["garden", "garden"]
    reweight:
      apply: True
      text: ["small"]
      weights: [-1, 1, 2, 4, 8]
    refine:
      apply: True
    replace:
      apply: False
  "2":
    prompt_init: "a photo of wooden beach house near the ocean"
    prompt_new: [
        "a photo of wooden beach house near the ocean covered with snow"
    ]
    steps: 50
    scale: 7.5
    self_replace_steps: 0.4
    cross_replace_steps: 0.8

    # modes
    localize:
      apply: False
      words: []
    reweight:
      apply: True
      text: ["snow"]
      weights: [-1, 1, 2, 4, 8]
    refine:
      apply: True
    replace:
      apply: False
